apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: ramezbassam97/flask-webhook:latest
          ports:
            - containerPort: 5000
          env:
            - name: JENKINS_URL
              value: "http://192.168.59.102:30080"
            - name: JENKINS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jenkins-token
                  key: token

