pipeline{
    agent{
        docker {
            image 'python:3.10'
            args '-v /var/run/docker.sock:/var/run/docker.sock' // To enable Docker inside the container
        }
    }

    environment {
        DOCKER_IMAGE = 'ramezbassam97/flask-webhook'
        //DOCKER_TAG = "latest"
        // Optional: to tag image by commit
        DOCKER_TAG = "${env.GIT_COMMIT}"
    }

    stages{
        stage("Fetch Flask App"){
            steps{
                git branch: 'dev', url: 'https://github.com/Ramezbassam/DevOps-Projects.git'
            }
        
        }
        stage("Validate Flask App") { 
            steps{
                sh 'python app.py & sleep 5 && pkill -f "python app.py"'
            }
        }
        stage("Build Docker Image") { 
            steps{
                sh 'docker build -t $DOCKER_IMAGE:$DOCKER_TAG'
            }
        }
        stage("Push to Docker Hub") { 
            steps{
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh "docker push $DOCKER_IMAGE:$DOCKER_TAG"
                }
            }
        }
    }
}
